CREATE TABLE user (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `username` varchar(100) DEFAULT NULL COMMENT '用户名',
  `password` varchar(100) DEFAULT NULL COMMENT '密码',
  `email` varchar(100) DEFAULT NULL COMMENT '邮箱',
  `mobile` varchar(100) DEFAULT NULL COMMENT '手机号码',
  `nickname` varchar(100) DEFAULT NULL COMMENT '昵称',
  `avatar` varchar(500) DEFAULT NULL COMMENT '头像',
  `signature` varchar(255) DEFAULT NULL COMMENT '个性签名',
  `real_name` varchar(100) DEFAULT NULL COMMENT '真实姓名',
  `identity_card` varchar(100) DEFAULT NULL COMMENT '证件号码',
  `gender` tinyint(4) DEFAULT '0' COMMENT '性别:0-保密;1-男;2-女',
  `age` tinyint(4) DEFAULT NULL COMMENT '年龄',
  `birthday` datetime DEFAULT NULL COMMENT '生日',
  `money` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '余额',
  `monetary` decimal(10,2) unsigned DEFAULT '0.00' COMMENT '总消费金额',
  `level` int(11) DEFAULT '0' COMMENT '等级',
  `integral` int(11) unsigned DEFAULT '0' COMMENT '积分',
  `history_integral` int(11) unsigned DEFAULT '0' COMMENT '历史积分',
  `vip_level` int(11) DEFAULT '0' COMMENT '会员等级',
  `vip_exp` int(11) unsigned DEFAULT '0' COMMENT '会员经验',
  `vip_time` datetime DEFAULT NULL COMMENT '会员时间',
  `email_verified_time` datetime DEFAULT NULL COMMENT '邮箱验证时间',
  `invite_code` varchar(100) DEFAULT NULL COMMENT '邀请码',
  `status` tinyint(4) DEFAULT '0' COMMENT '状态:0-禁用;1-正常',
  `team_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '团队ID',
  `promotion_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '推荐人ID',
  `promotion_time` datetime DEFAULT NULL COMMENT '推荐时间',
  `tenant_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '租户ID',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `delete_time` datetime DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY idx_user_username (`username`),
  KEY idx_user_email (`email`),
  KEY idx_user_mobile (`mobile`),
  KEY idx_user_nickname (`nickname`),
  KEY idx_user_real_name (`real_name`),
  KEY idx_user_identity_card (`identity_card`),
  KEY idx_user_invite_code (`invite_code`),
  KEY idx_user_status (`status`),
  KEY idx_user_team_id (`team_id`),
  KEY idx_user_promotion_id (`promotion_id`),
  KEY idx_user_tenant_id (`tenant_id`),
  KEY idx_user_create_time (`create_time`),
  KEY idx_user_update_time (`update_time`),
  KEY idx_user_delete_time (`delete_time`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
